image: node:6.9.4

pipelines:
  default:
    - step:
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.5
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn install
          - yarn test