image: node:8.10.0

pipelines:
  default:
    - parallel:
      - step:
          name: Behaviour
          script:
            - npm install
            - npm test
      - step:
          name: Linting
          script:
            - npm install
            - npm run lint
